### ISSUE TITLE
datasets in dbs not in popdb?

### ISSUE THREAD

**Issue by davidlange6** [dmwm/DDM#107]
Hi 
What does it mean if I find a dataset in dbs (and its valid) and not in the popularity? I have a bunch of examples, but e.g.:

/HSCPmchamp6_M-1000_TuneZ2star_13TeV_pythia6/RunIIWinter15GS-HSCP_customise_MCRUN2_71_V1-v2/GEN-SIM

thx

**Comment by nikmagini** [comment]
Hi David,

it simply means that the dataset has never been accessed with an access method measured by popularity (i.e. CRAB; plus WMAgent since Sep 2015).
We don't duplicate the DBS or PhEDEx file catalogs in PopDB, so unpopular dataset will not show up in PopDB (admittedly, the message from the API isn't clear though)

Cheers
N

**Comment by davidlange6** [comment]
Ok - I had assumed that getting data like this 

 [[1449964800000, 0]]

meant  no accesses (0 popularity)
